'use client';

import { useState, type FormEvent } from 'react';
type Product = { id: string; name: string };
type PreviewRow = { identity: string; sourceRow: number; subOrderNumber: string; date: string; quantity: number };
type Preview = { token: string; hash: string; rows: number; totalQuantity: number; grossInvoicePaise: number; dateRange: string; duplicates: { identity: string; count: number }[]; errors: string[]; previewRows: PreviewRow[]; mapped: number; unmapped: number };
type ApiError = { error?: string };

export default function ImportWorkspace({ connected, products }: { connected: boolean; products: Product[] }) {
  const [preview, setPreview] = useState<Preview>(); const [type, setType] = useState<'sales' | 'returns'>('sales'); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(false); const [associations, setAssociations] = useState<Record<string, string>>({});
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setPreview(undefined); const data = new FormData(event.currentTarget); data.set('type', type); const response = await fetch('/api/imports/preview', { method: 'POST', body: data }); const result = await response.json() as Preview | ApiError; setLoading(false); if (!response.ok) { setStatus((result as ApiError).error ?? 'Preview failed.'); return; } setPreview(result as Preview); setStatus('Preview ready for review.'); }
  async function commit() { if (!preview) return; setLoading(true); const response = await fetch('/api/imports/commit', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token: preview.token, associations }) }); const result = await response.json() as { events?: number } | ApiError; setLoading(false); setStatus(response.ok ? `Import receipt: ${(result as { events: number }).events} events.` : (result as ApiError).error ?? 'Commit failed.'); }
  const valid = Boolean(connected && preview?.token && !preview.errors.length && !preview.duplicates.length);
  return <><h1 className="text-3xl font-bold">Imports</h1><p className="mt-1 text-slate-600">Upload, validate, associate products, then commit the reviewed rows.</p><form onSubmit={upload} className="card mt-5 space-y-4" aria-busy={loading}><fieldset><legend className="font-bold">Event type</legend><label className="mr-5 inline-flex min-h-11 items-center gap-2"><input type="radio" checked={type === 'sales'} onChange={() => { setType('sales'); setPreview(undefined); }} />Sales</label><label className="inline-flex min-h-11 items-center gap-2"><input type="radio" checked={type === 'returns'} onChange={() => { setType('returns'); setPreview(undefined); }} />Returns</label></fieldset><label className="block font-medium">Spreadsheet<input className="input mt-1" name="file" type="file" accept=".xlsx,.csv" required onChange={() => setPreview(undefined)} /></label><button className="btn" disabled={loading}>{loading ? 'Working…' : 'Preview upload'}</button></form><p role="status" className="mt-3">{status}</p>{preview && <section className="card mt-5"><h2 className="text-xl font-bold">Preview</h2><dl className="mt-3 grid grid-cols-2 gap-3"><div><dt>Rows</dt><dd>{preview.rows}</dd></div><div><dt>Total quantity</dt><dd>{preview.totalQuantity}</dd></div><div><dt>Invoice value</dt><dd>₹{(preview.grossInvoicePaise / 100).toFixed(2)}</dd></div><div><dt>Unmapped</dt><dd>{preview.unmapped}</dd></div><div className="col-span-2"><dt>File hash</dt><dd className="break-all">{preview.hash}</dd></div></dl>{(preview.errors.length > 0 || preview.duplicates.length > 0) && <div role="alert" className="mt-4 rounded-md bg-red-50 p-3 text-red-800"><h3 className="font-bold">Resolve before commit</h3>{preview.errors.map((error) => <p key={error}>{error}</p>)}{preview.duplicates.map((duplicate) => <p key={duplicate.identity}>{duplicate.identity}: {duplicate.count} duplicate rows</p>)}</div>}<div className="table-wrap mt-4"><table className="table"><caption>Parsed rows and product associations</caption><thead><tr><th>Sub-order</th><th>Date</th><th>Quantity</th><th>Product</th></tr></thead><tbody>{preview.previewRows.map((row) => <tr key={row.identity}><td>{row.subOrderNumber}</td><td>{row.date}</td><td>{row.quantity}</td><td><label className="sr-only" htmlFor={`product-${row.sourceRow}`}>Product for {row.subOrderNumber}</label><select id={`product-${row.sourceRow}`} className="input" value={associations[row.identity] ?? ''} onChange={(event) => setAssociations({ ...associations, [row.identity]: event.target.value })}><option value="">Unmapped</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></td></tr>)}</tbody></table></div><button type="button" className="btn mt-4" disabled={!valid || loading} onClick={commit}>{loading ? 'Working…' : 'Commit import'}</button>{!connected && <p role="status" className="mt-2 text-slate-600">Connect MongoDB to save changes.</p>}</section>}</>;
}
